apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis2
  labels:
    app: redis2
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-2
