apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis1
  labels:
    app: redis1
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-1
