apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis4
  labels:
    app: redis4
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-4
