apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis01
