apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis5
  labels:
    app: redis5
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-5
