apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis0
  labels:
    app: redis0
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-0
