apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis3
  labels:
    app: redis3
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/redis-3
