apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis2
  labels:
    app: redis2
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: redis2
