apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis-cluster
  labels:
    app: redis-cluster

spec:
  serviceName: redis-cluster-service
  selector:
    matchLabels:
      app: redis-cluster

  replicas: 6

  template:
    metadata:
      labels:
        app: redis-cluster

    spec:
      containers:
        - name: redis
          command: ["redis-server", "/conf/redis.conf"]

          image: redis:5.0.1-alpine
          ports:
            - containerPort: 6379
              name: client

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false

      volumes:
        - name: conf
          configMap:
            name: redis-cluster-configmap

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  clusterIP: None
  selector:
    app: redis-cluster
  ports:
    - port: 6379
      name: redis-cluster
  publishNotReadyAddresses: true
