apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis-cluster

spec:
  selector:
    matchLabels:
      app: redis-cluster
  serviceName: redis-cluster
  replicas: 6

  template:
    metadata:
      labels:
        app: redis-cluster

    spec:
      containers:
        - name: redis
          # command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
          command: ["redis-server", "/conf/redis.conf"]

          image: redis:5.0.1-alpine
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false

      volumes:
        - name: conf
          configMap:
            name: redis-cluster-configmap

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
